name: 'NPM Setup'
description: 'Setup NodeJS environment and node_modules (install & cache dependencies)'

inputs:
  NPM_TOKEN:
    description: 'NPM access token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        registry-url: 'https://registry.npmjs.org/'
      env:
        NODE_AUTH_TOKEN: ${{ inputs.NPM_TOKEN }}

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: modules-${{ hashFiles('yarn.lock') }}

    - name: Install dependencies
      shell: sh
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile
