name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0


      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.3.11

      # This enables task distribution via Nx Cloud
      # - run: bunx nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"


      - run: bun install --no-cache
      - uses: nrwl/nx-set-shas@v4


      - run: bun nx-cloud record -- bun lint
      - run: bun nx affected -t test build
      # Nx Cloud recommends fixes for failures to help you get CI green faster. Learn more: https://nx.dev/ci/features/self-healing-ci
      - run: bun nx fix-ci
        if: always()
