name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          filter: tree:0
          fetch-depth: 0

      - name: Setup toolchains with mise
        uses: jdx/mise-action@v3

      - run: bun install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v5


      - run: bun nx-cloud record -- bun lint
      - run: bun nx affected -t test build
      # Nx Cloud recommends fixes for failures to help you get CI green faster. Learn more: https://nx.dev/ci/features/self-healing-ci
      - run: bun nx fix-ci
        if: always()
