name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup toolchains with mise
        uses: jdx/mise-action@v3

      - run: bun install --frozen-lockfile

      - name: Build
        run: bun nx build nx-aws-cache

      - name: Publish
        run: bun nx release publish
        env:
          BUN_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
